### ISSUE TITLE
RTX 3090 failure

### ISSUE THREAD

**Issue by kizunasunhy** [ELS-RD/kernl#121]
Just run the demo code:
```
import torch
>>> from transformers import AutoModel
>>> from kernl.model_optimization import optimize_model
>>> from transformers import RobertaTokenizer
>>> tokenizer = RobertaTokenizer.from_pretrained("roberta-base")
>>> inputs = tokenizer("Hello, my dog is cute", return_tensors="pt").to('cuda')
>>> model = AutoModel.from_pretrained('roberta-base').eval().cuda()
>>> optimized_model = optimize_model(model)
>>> with torch.inference_mode(), torch.cuda.amp.autocast():
...     outputs = optimized_model(**inputs)
```
and got this error:
```
----------------------------------------
TORCHDYNAMO: backend compiler failed
Traceback (most recent call last):
  File "<string>", line 21, in _layer_norm_fwd_fused_single_pass
KeyError: ('2-.-0-.-0-05cd73e2a4bdbeb71ab52fd66d1a1ac4-cfed90d463fc30ccffb0eb2fd26372d3-a357695982511d203a134df772c7b4a1-2121719c12e3ab66746f4a57f276d42e-0f76008a374e725ca29ccb33f1ba668f-dc48432b6b79843e2f9c7ad2e7355f59-f40d73592c2578180d3d8e3f64e3957d-0dd03b0bd512a184b3512b278d9dfa59-d7c2e52f8151bec157e9a17a1ec37dd3', (torch.float16, torch.float16, torch.float16, torch.float16, torch.float32, torch.float32, 'i32', 'i32', 'fp32'), (True, False, 1024), (True, True, True, True, True, True, (True, False), (True, False), (False,)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/miniconda3/envs/kernl/lib/python3.9/site-packages/torchdynamo/output_graph.py", line 341, in call_user_compiler
    compiled_fn = self.compiler_fn(gm, self.example_inputs())
  File "/root/kernl/src/kernl/model_optimization.py", line 46, in compiler
    return cuda_graphs_wrapper(gm, example_inputs, pool=pool)
  File "/root/kernl/src/kernl/implementations/cuda_graph.py", line 40, in cuda_graphs_wrapper
    model(*inputs)
  File "/home/miniconda3/envs/kernl/lib/python3.9/site-packages/torch/fx/graph_module.py", line 652, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/home/miniconda3/envs/kernl/lib/python3.9/site-packages/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/home/miniconda3/envs/kernl/lib/python3.9/site-packages/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/home/miniconda3/envs/kernl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.18", line 19, in forward
    layer_norm_wrapper = kernl_optimizer_layer_norm_layer_norm_wrapper(add_3, layernorm);  add_3 = layernorm = None
  File "/root/kernl/src/kernl/optimizer/layer_norm.py", line 29, in layer_norm_wrapper
    return layer_norm(v, layernorm.weight, layernorm.bias, layernorm.eps)
  File "/root/kernl/src/kernl/implementations/layer_norm.py", line 319, in layer_norm
    return LayerNorm.apply(x, weight, bias, eps, implementation, use_rms_norm)
  File "/home/miniconda3/envs/kernl/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 116, in decorate_fwd
    return fwd(*_cast(args, cast_inputs), **_cast(kwargs, cast_inputs))
  File "/root/kernl/src/kernl/implementations/layer_norm.py", line 290, in forward
    implementation[(M,)](
  File "/home/miniconda3/envs/kernl/lib/python3.9/site-packages/triton/runtime/jit.py", line 106, in launcher
    return self.run(*args, grid=grid, **kwargs)
  File "<string>", line 42, in _layer_norm_fwd_fused_single_pass
  File "/home/miniconda3/envs/kernl/lib/python3.9/site-packages/triton/compiler.py", line 1215, in compile
    asm, shared, kernel_name = _compile(fn, signature, device, constants, configs[0], num_warps, num_stages,
  File "/home/miniconda3/envs/kernl/lib/python3.9/site-packages/triton/compiler.py", line 900, in _compile
    name, asm, shared_mem = _triton.code_gen.compile_ttir(backend, module, device, num_warps, num_stages, extern_libs, cc)
RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/fileuynWNC, line 79; fatal   : Parsing error near ':': syntax error
ptxas fatal   : Ptx assembly aborted due to errors

----------------------------------------
ERROR:root:Error while processing frame
Traceback (most recent call last):
  File "<string>", line 21, in _layer_norm_fwd_fused_single_pass
KeyError: ('2-.-0-.-0-05cd73e2a4bdbeb71ab52fd66d1a1ac4-cfed90d463fc30ccffb0eb2fd26372d3-a357695982511d203a134df772c7b4a1-2121719c12e3ab66746f4a57f276d42e-0f76008a374e725ca29ccb33f1ba668f-dc48432b6b79843e2f9c7ad2e7355f59-f40d73592c2578180d3d8e3f64e3957d-0dd03b0bd512a184b3512b278d9dfa59-d7c2e52f8151bec157e9a17a1ec37dd3', (torch.float16, torch.float16, torch.float16, torch.float16, torch.float32, torch.float32, 'i32', 'i32', 'fp32'), (True, False, 1024), (True, True, True, True, True, True, (True, False), (True, False), (False,)))

During handling of the above exception, another exception occurred:
......
```
the version is:
pytorch: 1.12.0 cu 11.6
torchdynamo: 1.12.0
triton: 2.0.0.dev20221001
transformers: 4.23.1

Could anyone help? Thanks.

**Comment by pommedeterresautee** [comment]
Not sure if it's related but the version of torchdynamo should be `torchdynamo-1.13.0.dev0`.
I have run the script on my machine and it works on both REPL and as python script.
I am under Python 3.9
If using the right torchdynamo doesn't help, have you tried the Docker image?

**Comment by kizunasunhy** [comment]
> Not sure if it's related but the version of torchdynamo should be `torchdynamo-1.13.0.dev0`. I have run the script on my machine and it works on both REPL and as python script. I am under Python 3.9 If using the right torchdynamo doesn't help, have you tried the Docker image?

Thank you for your help. However a new error appeared after I switched to torchdynamo 1.13.0
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/root/kernl/src/kernl/model_optimization.py", line 49, in run
    with torchdynamo.optimize(compiler):
  File "/root/kernl/torchdynamo-1.13/torchdynamo/eval_frame.py", line 116, in __enter__
    raise RuntimeError(
RuntimeError: torchdynamo.optimize(...) is used with a context manager. Please refer to https://github.com/pytorch/usage-example to use torchdynamo.optimize(...) as an annotation/decorator. 
```
Have you ever seen this?

**Comment by kizunasunhy** [comment]
And one more thing. We should install cuda 11.6 for system, otherwise, if we only install pytorch with cuda 11.6, then the torchdynamo may not execute well. So better to verify by:
```
nvcc --version
```
and then verify the installation of torchdynamo

**Comment by kizunasunhy** [comment]
Alright.. after accurately changed torchdynamo to 1.13.0.dev0 by:
```
git clone --filter=blob:none --quiet https://github.com/pytorch/torchdynamo.git /tmp/pip-install-xbitcrmu/torchdynamo_b51b4ccfd53740999fb89c0b03e83fbb
cd /tmp/pip-install-xbitcrmu/torchdynamo_b51b4ccfd53740999fb89c0b03e83fbb
git checkout 6bd5b8bb8888d5dab0b9574b20f00de975eebc72
```
Finally worked. But the last step:
```
with torch.inference_mode(), torch.cuda.amp.autocast():
...     outputs = optimized_model(**inputs)
```
took around 5-10 seconds to produce a result.
Did I do it wrong? How to correctly use it? Thank you.

**Comment by pommedeterresautee** [comment]
:-) wanted to write to you that I have not CUDA on my machine (life is now much better) and it works.
Regarding the timings, it's because you don't warmup.

Have a look to:
* https://github.com/ELS-RD/kernl/blob/main/tutorial/bert%20e2e.ipynb (XNLI + Roberta)
* https://github.com/ELS-RD/kernl/blob/main/tutorial/t5%20e2e.ipynb (text generation on T5)

Warmup takes time but we are currently working to reduce it by a *large* margin and making it optional.

Let me know if you have other questions.

**Comment by kizunasunhy** [comment]
> :-) wanted to write to you that I have not CUDA on my machine (life is now much better) and it works. Regarding the timings, it's because you don't warmup.
> 
> Have a look to:
> 
> * https://github.com/ELS-RD/kernl/blob/main/tutorial/bert%20e2e.ipynb (XNLI + Roberta)
> * https://github.com/ELS-RD/kernl/blob/main/tutorial/t5%20e2e.ipynb (text generation on T5)
> 
> Warmup takes time but we are currently working to reduce it by a _large_ margin and making it optional.
> 
> Let me know if you have other questions.

Thank you and now it worked!

**Comment by pommedeterresautee** [comment]
ok tks, closing
