### ISSUE TITLE
Triton errors while converting Swin Transformer

### ISSUE THREAD

**Issue by CodeJjang** [ELS-RD/kernl#137]
Following code using Swin Transformer works:
```
from transformers import AutoFeatureExtractor, SwinModel
import torch
from datasets import load_dataset

dataset = load_dataset("huggingface/cats-image")
image = dataset["test"]["image"][0]

feature_extractor = AutoFeatureExtractor.from_pretrained("microsoft/swin-tiny-patch4-window7-224")
model = SwinModel.from_pretrained("microsoft/swin-tiny-patch4-window7-224")

inputs = feature_extractor(image, return_tensors="pt")

with torch.no_grad():
    outputs = model(**inputs)

last_hidden_states = outputs.last_hidden_state
list(last_hidden_states.shape)
```
However while trying to optimize the model, triton raises an error:
```
import torch
from transformers import AutoModel
from kernl.model_optimization import optimize_model

model_name = "microsoft/swin-tiny-patch4-window7-224"
model = AutoModel.from_pretrained(model_name).eval().cuda()
optimized_model = optimize_model(model)

inputs = feature_extractor(image, return_tensors="pt")
inputs['pixel_values'] = inputs['pixel_values'].cuda().half()

with torch.inference_mode(), torch.cuda.amp.autocast():
    outputs = optimized_model(**inputs)

last_hidden_states = outputs.last_hidden_state
list(last_hidden_states.shape)
```

```
Some weights of the model checkpoint at microsoft/swin-tiny-patch4-window7-224 were not used when initializing SwinModel: ['classifier.bias', 'classifier.weight']
- This IS expected if you are initializing SwinModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing SwinModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
----------------------------------------
TORCHDYNAMO: backend compiler failed
Traceback (most recent call last):
  File "<string>", line 21, in _layer_norm_fwd_fused_single_pass
KeyError: ('2-.-0-.-0-b2c1ddfcb426cbdb0f3c0be579181880-cfed90d463fc30ccffb0eb2fd26372d3-a357695982511d203a134df772c7b4a1-2121719c12e3ab66746f4a57f276d42e-0f76008a374e725ca29ccb33f1ba668f-dc48432b6b79843e2f9c7ad2e7355f59-f40d73592c2578180d3d8e3f64e3957d-0dd03b0bd512a184b3512b278d9dfa59-d7c2e52f8151bec157e9a17a1ec37dd3', (torch.float16, torch.float16, torch.float16, torch.float16, torch.float32, torch.float32, 'i32', 'i32', 'fp32'), (True, False, 128), (True, True, True, True, True, True, (True, False), (True, False), (False,)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/output_graph.py", line 362, in call_user_compiler
    compiled_fn = self.compiler_fn(gm, self.example_inputs())
  File "/home/ubuntu/dev/kernl/src/kernl/model_optimization.py", line 46, in compiler
    return cuda_graphs_wrapper(gm, example_inputs, pool=pool)
  File "/home/ubuntu/dev/kernl/src/kernl/implementations/cuda_graph.py", line 40, in cuda_graphs_wrapper
    model(*inputs)
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torch/fx/graph_module.py", line 652, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.317", line 7, in forward
    layer_norm_wrapper = kernl_optimizer_layer_norm_layer_norm_wrapper(hidden_states, layernorm);  layernorm = None
  File "/home/ubuntu/dev/kernl/src/kernl/optimizer/layer_norm.py", line 29, in layer_norm_wrapper
    return layer_norm(v, layernorm.weight, layernorm.bias, layernorm.eps)
  File "/home/ubuntu/dev/kernl/src/kernl/implementations/layer_norm.py", line 319, in layer_norm
    return LayerNorm.apply(x, weight, bias, eps, implementation, use_rms_norm)
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 116, in decorate_fwd
    return fwd(*_cast(args, cast_inputs), **_cast(kwargs, cast_inputs))
  File "/home/ubuntu/dev/kernl/src/kernl/implementations/layer_norm.py", line 290, in forward
    implementation[(M,)](
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/triton/runtime/jit.py", line 106, in launcher
    return self.run(*args, grid=grid, **kwargs)
  File "<string>", line 42, in _layer_norm_fwd_fused_single_pass
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/triton/compiler.py", line 1215, in compile
    asm, shared, kernel_name = _compile(fn, signature, device, constants, configs[0], num_warps, num_stages,
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/triton/compiler.py", line 900, in _compile
    name, asm, shared_mem = _triton.code_gen.compile_ttir(backend, module, device, num_warps, num_stages, extern_libs, cc)
RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/fileTRGV2e, line 70; fatal   : Parsing error near ':': syntax error
ptxas fatal   : Ptx assembly aborted due to errors

----------------------------------------
ERROR:root:Error while processing frame
Traceback (most recent call last):
  File "<string>", line 21, in _layer_norm_fwd_fused_single_pass
KeyError: ('2-.-0-.-0-b2c1ddfcb426cbdb0f3c0be579181880-cfed90d463fc30ccffb0eb2fd26372d3-a357695982511d203a134df772c7b4a1-2121719c12e3ab66746f4a57f276d42e-0f76008a374e725ca29ccb33f1ba668f-dc48432b6b79843e2f9c7ad2e7355f59-f40d73592c2578180d3d8e3f64e3957d-0dd03b0bd512a184b3512b278d9dfa59-d7c2e52f8151bec157e9a17a1ec37dd3', (torch.float16, torch.float16, torch.float16, torch.float16, torch.float32, torch.float32, 'i32', 'i32', 'fp32'), (True, False, 128), (True, True, True, True, True, True, (True, False), (True, False), (False,)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/output_graph.py", line 362, in call_user_compiler
    compiled_fn = self.compiler_fn(gm, self.example_inputs())
  File "/home/ubuntu/dev/kernl/src/kernl/model_optimization.py", line 46, in compiler
    return cuda_graphs_wrapper(gm, example_inputs, pool=pool)
  File "/home/ubuntu/dev/kernl/src/kernl/implementations/cuda_graph.py", line 40, in cuda_graphs_wrapper
    model(*inputs)
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torch/fx/graph_module.py", line 652, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.317", line 7, in forward
    layer_norm_wrapper = kernl_optimizer_layer_norm_layer_norm_wrapper(hidden_states, layernorm);  layernorm = None
  File "/home/ubuntu/dev/kernl/src/kernl/optimizer/layer_norm.py", line 29, in layer_norm_wrapper
    return layer_norm(v, layernorm.weight, layernorm.bias, layernorm.eps)
  File "/home/ubuntu/dev/kernl/src/kernl/implementations/layer_norm.py", line 319, in layer_norm
    return LayerNorm.apply(x, weight, bias, eps, implementation, use_rms_norm)
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 116, in decorate_fwd
    return fwd(*_cast(args, cast_inputs), **_cast(kwargs, cast_inputs))
  File "/home/ubuntu/dev/kernl/src/kernl/implementations/layer_norm.py", line 290, in forward
    implementation[(M,)](
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/triton/runtime/jit.py", line 106, in launcher
    return self.run(*args, grid=grid, **kwargs)
  File "<string>", line 42, in _layer_norm_fwd_fused_single_pass
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/triton/compiler.py", line 1215, in compile
    asm, shared, kernel_name = _compile(fn, signature, device, constants, configs[0], num_warps, num_stages,
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/triton/compiler.py", line 900, in _compile
    name, asm, shared_mem = _triton.code_gen.compile_ttir(backend, module, device, num_warps, num_stages, extern_libs, cc)
RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/fileTRGV2e, line 70; fatal   : Parsing error near ':': syntax error
ptxas fatal   : Ptx assembly aborted due to errors


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/eval_frame.py", line 148, in catch_errors
    return callback(frame, cache_size)
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/convert_frame.py", line 347, in _convert_frame
    result = inner_convert(frame, cache_size)
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/convert_frame.py", line 108, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/convert_frame.py", line 288, in _convert_frame_assert
    code = transform_code_object(frame.f_code, transform)
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/bytecode_transformation.py", line 338, in transform_code_object
    transformations(instructions, code_options)
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/convert_frame.py", line 264, in transform
    tracer.run()
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/symbolic_convert.py", line 312, in run
    and self.step()
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/symbolic_convert.py", line 290, in step
    getattr(self, inst.opname)(inst)
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/symbolic_convert.py", line 158, in wrapper
    self.output.compile_subgraph(self)
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/output_graph.py", line 307, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/output_graph.py", line 348, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/ubuntu/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/output_graph.py", line 371, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torchdynamo.exc.BackendCompilerFailed: compiler raised RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/fileTRGV2e, line 70; fatal   : Parsing error near ':': syntax error
ptxas fatal   : Ptx assembly aborted due to errors


You can suppress this exception and fall back to eager by setting:
    torchdynamo.config.raise_on_backend_error = False
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File <string>:21, in _layer_norm_fwd_fused_single_pass(Out, A, Weight, Bias, Mean, Rstd, stride_row_a, N, eps, HAS_BIAS, IS_RMSNORM, BLOCK_SIZE, grid, num_warps, num_stages, extern_libs, stream, warmup)

KeyError: ('2-.-0-.-0-b2c1ddfcb426cbdb0f3c0be579181880-cfed90d463fc30ccffb0eb2fd26372d3-a357695982511d203a134df772c7b4a1-2121719c12e3ab66746f4a57f276d42e-0f76008a374e725ca29ccb33f1ba668f-dc48432b6b79843e2f9c7ad2e7355f59-f40d73592c2578180d3d8e3f64e3957d-0dd03b0bd512a184b3512b278d9dfa59-d7c2e52f8151bec157e9a17a1ec37dd3', (torch.float16, torch.float16, torch.float16, torch.float16, torch.float32, torch.float32, 'i32', 'i32', 'fp32'), (True, False, 128), (True, True, True, True, True, True, (True, False), (True, False), (False,)))

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/output_graph.py:362, in OutputGraph.call_user_compiler(self, gm)
    361 try:
--> 362     compiled_fn = self.compiler_fn(gm, self.example_inputs())
    363     assert callable(compiled_fn), "compiler_fn did not return callable"

File ~/dev/kernl/src/kernl/model_optimization.py:46, in optimize_model.<locals>.compiler(gm, example_inputs)
     45 dynamo_backend_ofi(gm)
---> 46 return cuda_graphs_wrapper(gm, example_inputs, pool=pool)

File ~/dev/kernl/src/kernl/implementations/cuda_graph.py:40, in cuda_graphs_wrapper(model, inputs, copy_outputs, pool)
     39     for _ in range(2):
---> 40         model(*inputs)
     41 stream.synchronize()

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torch/fx/graph_module.py:652, in GraphModule.recompile.<locals>.call_wrapped(self, *args, **kwargs)
    651 def call_wrapped(self, *args, **kwargs):
--> 652     return self._wrapped_call(self, *args, **kwargs)

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torch/fx/graph_module.py:277, in _WrappedCall.__call__(self, obj, *args, **kwargs)
    276 else:
--> 277     raise e

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torch/fx/graph_module.py:267, in _WrappedCall.__call__(self, obj, *args, **kwargs)
    266     else:
--> 267         return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
    268 except Exception as e:

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used

File <eval_with_key>.317:7, in forward(self, hidden_states)
      6 layernorm = self.self_layers_0__blocks_0__layernorm_before
----> 7 layer_norm_wrapper = kernl_optimizer_layer_norm_layer_norm_wrapper(hidden_states, layernorm);  layernorm = None
      8 view = layer_norm_wrapper.view(1, 56, 56, 96);  layer_norm_wrapper = None

File ~/dev/kernl/src/kernl/optimizer/layer_norm.py:29, in layer_norm_wrapper(v, layernorm)
     27     layernorm.bias.data = layernorm.bias.data.half()
---> 29 return layer_norm(v, layernorm.weight, layernorm.bias, layernorm.eps)

File ~/dev/kernl/src/kernl/implementations/layer_norm.py:319, in layer_norm(x, weight, bias, eps, implementation, use_rms_norm)
    311 def layer_norm(
    312     x: torch.Tensor,
    313     weight: torch.Tensor,
   (...)
    317     use_rms_norm: bool = False,
    318 ):
--> 319     return LayerNorm.apply(x, weight, bias, eps, implementation, use_rms_norm)

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py:116, in custom_fwd.<locals>.decorate_fwd(*args, **kwargs)
    115     with autocast(enabled=False):
--> 116         return fwd(*_cast(args, cast_inputs), **_cast(kwargs, cast_inputs))
    117 else:

File ~/dev/kernl/src/kernl/implementations/layer_norm.py:290, in LayerNorm.forward(ctx, x, weight, bias, eps, implementation, use_rms_norm)
    289 num_warps = min(max(BLOCK_SIZE // 256, 1), 8)
--> 290 implementation[(M,)](
    291     Out=out,
    292     A=a_arg,
    293     Weight=weight,
    294     Bias=bias if bias is not None else a_arg,
    295     Mean=mean,
    296     Rstd=std,
    297     stride_row_a=a_arg.stride(0),
    298     N=N,
    299     eps=eps,
    300     HAS_BIAS=bias is not None,
    301     IS_RMSNORM=use_rms_norm,
    302     BLOCK_SIZE=BLOCK_SIZE,
    303     num_warps=num_warps,
    304 )
    305 ctx.save_for_backward(x, mean, std, weight)

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/triton/runtime/jit.py:106, in KernelInterface.__getitem__.<locals>.launcher(*args, **kwargs)
    105 def launcher(*args, **kwargs):
--> 106     return self.run(*args, grid=grid, **kwargs)

File <string>:42, in _layer_norm_fwd_fused_single_pass(Out, A, Weight, Bias, Mean, Rstd, stride_row_a, N, eps, HAS_BIAS, IS_RMSNORM, BLOCK_SIZE, grid, num_warps, num_stages, extern_libs, stream, warmup)

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/triton/compiler.py:1215, in compile(fn, signature, device, constants, num_warps, num_stages, extern_libs, configs, cc, warm_cache_only)
   1212 if not fn_cache_manager.has_file(cubin_name) or \
   1213    not fn_cache_manager.has_file(data_name) or \
   1214    not fn_cache_manager.has_file(ptx_name):
-> 1215     asm, shared, kernel_name = _compile(fn, signature, device, constants, configs[0], num_warps, num_stages,
   1216                                         extern_libs, "cubin", cc)
   1217     metadata = {"name": kernel_name, "shared": shared, "num_warps": num_warps, "num_stages": num_stages}

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/triton/compiler.py:900, in _compile(fn, signature, device, constants, specialization, num_warps, num_stages, extern_libs, output, cc)
    899     extern_libs = dict()
--> 900 name, asm, shared_mem = _triton.code_gen.compile_ttir(backend, module, device, num_warps, num_stages, extern_libs, cc)
    901 return asm, shared_mem, name

RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/fileTRGV2e, line 70; fatal   : Parsing error near ':': syntax error
ptxas fatal   : Ptx assembly aborted due to errors


The above exception was the direct cause of the following exception:

BackendCompilerFailed                     Traceback (most recent call last)
Cell In [11], line 12
     10 inputs['pixel_values'] = inputs['pixel_values'].cuda()
     11 with torch.inference_mode(), torch.cuda.amp.autocast(enabled=True, dtype=torch.float16, cache_enabled=True):
---> 12     outputs = optimized_model(**inputs)
     14 last_hidden_states = outputs.last_hidden_state
     15 list(last_hidden_states.shape)

File ~/dev/kernl/src/kernl/model_optimization.py:50, in optimize_model.<locals>.run(*args, **kwargs)
     48 def run(*args, **kwargs):
     49     with torchdynamo.optimize(compiler):
---> 50         return original_model.forward2(*args, **kwargs)

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/transformers/models/swin/modeling_swin.py:978, in SwinModel.forward(self, pixel_values, bool_masked_pos, head_mask, output_attentions, output_hidden_states, return_dict)
    974 head_mask = self.get_head_mask(head_mask, len(self.config.depths))
    976 embedding_output, input_dimensions = self.embeddings(pixel_values, bool_masked_pos=bool_masked_pos)
--> 978 encoder_outputs = self.encoder(
    979     embedding_output,
    980     input_dimensions,
    981     head_mask=head_mask,
    982     output_attentions=output_attentions,
    983     output_hidden_states=output_hidden_states,
    984     return_dict=return_dict,
    985 )
    987 sequence_output = encoder_outputs[0]
    988 sequence_output = self.layernorm(sequence_output)

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/eval_frame.py:148, in catch_errors_wrapper.<locals>.catch_errors(frame, cache_size)
    146         return None
    147     with compile_lock:
--> 148         return callback(frame, cache_size)
    149 except Exception:
    150     logging.basicConfig()

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/convert_frame.py:347, in convert_frame.<locals>._convert_frame(frame, cache_size)
    345 counters["frames"]["total"] += 1
    346 try:
--> 347     result = inner_convert(frame, cache_size)
    348     counters["frames"]["ok"] += 1
    349     return result

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/convert_frame.py:108, in wrap_convert_context.<locals>._fn(*args, **kwargs)
    106 torch.fx.graph_module._forward_from_src = fx_forward_from_src_skip_result
    107 try:
--> 108     return fn(*args, **kwargs)
    109 finally:
    110     torch._C._set_grad_enabled(prior_grad_mode)

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/convert_frame.py:288, in convert_frame_assert.<locals>._convert_frame_assert(frame, cache_size)
    286 for attempt in itertools.count():
    287     try:
--> 288         code = transform_code_object(frame.f_code, transform)
    289         orig_code_map[code] = frame.f_code
    290         break

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/bytecode_transformation.py:338, in transform_code_object(code, transformations, safe)
    334 assert len(code_options["co_varnames"]) == code_options["co_nlocals"]
    336 instructions = cleaned_instructions(code, safe)
--> 338 transformations(instructions, code_options)
    340 fix_vars(instructions, code_options)
    342 dirty = True

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/convert_frame.py:264, in convert_frame_assert.<locals>._convert_frame_assert.<locals>.transform(instructions, code_options)
    253 nonlocal output
    254 tracer = InstructionTranslator(
    255     instructions,
    256     frame.f_code,
   (...)
    262     one_graph,
    263 )
--> 264 tracer.run()
    265 output = tracer.output
    266 assert output.output_instructions

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/symbolic_convert.py:312, in InstructionTranslatorBase.run(self)
    307 def run(self):
    308     try:
    309         while (
    310             self.instruction_pointer is not None
    311             and not self.output.should_exit
--> 312             and self.step()
    313         ):
    314             pass
    315     except (
    316         exc.BackendCompilerFailed,
    317         exc.RestartAnalysis,
   (...)
    320         exc.Unsupported,
    321     ):

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/symbolic_convert.py:290, in InstructionTranslatorBase.step(self)
    288     if not hasattr(self, inst.opname):
    289         unimplemented(f"missing: {inst.opname}")
--> 290     getattr(self, inst.opname)(inst)
    291     return inst.opname != "RETURN_VALUE"
    292 except Unsupported as exc:

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/symbolic_convert.py:158, in break_graph_if_unsupported.<locals>.decorator.<locals>.wrapper(self, inst)
    156     exc.add_to_stats("graph_break")
    157 self.restore_graphstate(state)
--> 158 self.output.compile_subgraph(self)
    159 self.popn(push - dis.stack_effect(inst.opcode, inst.arg))
    161 for _ in range(push):

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/output_graph.py:307, in OutputGraph.compile_subgraph(self, tx, partial_convert)
    304 output = []
    305 if count_calls(self.graph) != 0 or len(pass2.graph_outputs) != 0:
    306     output.extend(
--> 307         self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
    308     )
    310     if len(pass2.graph_outputs) != 0:
    311         output.append(pass2.create_store(graph_output_var))

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/output_graph.py:348, in OutputGraph.compile_and_call_fx_graph(self, tx, rv, root)
    346 gm.recompile()
    347 name = unique_id("__compiled_fn")
--> 348 compiled_fn = self.call_user_compiler(gm)
    349 compiled_fn = torchdynamo.disable(compiled_fn)
    350 counters["stats"]["unique_graphs"] += 1

File ~/anaconda3/envs/pytorch_113_p39/lib/python3.9/site-packages/torchdynamo/output_graph.py:371, in OutputGraph.call_user_compiler(self, gm)
    369     compiled_fn = gm.forward
    370     if config.raise_on_backend_error:
--> 371         raise BackendCompilerFailed(self.compiler_fn, e) from e
    372 return compiled_fn

BackendCompilerFailed: compiler raised RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/fileTRGV2e, line 70; fatal   : Parsing error near ':': syntax error
ptxas fatal   : Ptx assembly aborted due to errors


You can suppress this exception and fall back to eager by setting:
    torchdynamo.config.raise_on_backend_error = False
```

PyTorch 1.12, CUDA 1.16

**Comment by gaetansnl** [comment]
Used this code. Segfault when cudagraph is enabled, but working when disabled. It needs more investigations
```
    dataset = load_dataset("huggingface/cats-image")
    image = dataset["test"]["image"][0]

    feature_extractor = AutoFeatureExtractor.from_pretrained("microsoft/swin-tiny-patch4-window7-224")
    model = SwinModel.from_pretrained("microsoft/swin-tiny-patch4-window7-224").to("cuda")
    inputs = feature_extractor(image, return_tensors="pt").to("cuda")
    expected = model(**inputs).last_hidden_state.clone()

    optimize_model(model.encoder)

    with torch.inference_mode(), torch.autocast(dtype=torch.float16, cache_enabled=True, device_type="cuda"):
        outputs = model(**inputs)

    last_hidden_states = outputs.last_hidden_state.clone()

    assert_all_close(expected.float(), last_hidden_states.float(), atol=1e-1, rtol=1e-1)
```
