### ISSUE TITLE
GPT-J Internal Triton PTX codegen error: 

### ISSUE THREAD

**Issue by zelcookie** [ELS-RD/kernl#146]
When I try to run optimized gpt-j I get an error:

```
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
from kernl.model_optimization import optimize_model

params = {
 'num_beams': 2,
 'do_sample': False,
 'max_new_tokens': 65,
 'use_cache': True,
 'no_repeat_ngram_size': 5,
 'num_return_sequences': 1}

 
model_name = 'EleutherAI/gpt-j-6B'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name).eval().cuda()
model.forward = optimize_model(model)
inputs = tokenizer("Hello world", return_tensors="pt").to('cuda')

with torch.inference_mode(), torch.cuda.amp.autocast():
    outputs = model.generate(
                inputs["input_ids"],
                **params

            )

```
```
TORCHDYNAMO: backend compiler failed
Traceback (most recent call last):
  File "<string>", line 21, in _layer_norm_fwd_fused_single_pass
KeyError: ('2-.-0-.-0-aced2afef9a9131c1822ef1dc83cefd3-cfed90d463fc30ccffb0eb2fd26372d3-a357695982511d203a134df772c7b4a1-2121719c12e3ab66746f4a57f276d42e-0f76008a374e725ca29ccb33f1ba668f-dc48432b6b79843e2f9c7ad2e7355f59-f40d73592c2578180d3d8e3f64e3957d-0dd03b0bd512a184b3512b278d9dfa59-d7c2e52f8151bec157e9a17a1ec37dd3', (torch.float16, torch.float16, torch.float16, torch.float16, torch.float32, torch.float32, 'i32', 'i32', 'fp32'), (True, False, 4096), (True, True, True, True, True, True, (True, False), (True, False), (False,)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mikhail/venv/lib/python3.9/site-packages/torchdynamo/output_graph.py", line 362, in call_user_compiler
    compiled_fn = self.compiler_fn(gm, self.example_inputs())
  File "/home/mikhail/kernl/src/kernl/model_optimization.py", line 46, in compiler
    return cuda_graphs_wrapper(gm, example_inputs, pool=pool)
  File "/home/mikhail/kernl/src/kernl/implementations/cuda_graph.py", line 40, in cuda_graphs_wrapper
    model(*inputs)
  File "/home/mikhail/venv/lib/python3.9/site-packages/torch/fx/graph_module.py", line 652, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/home/mikhail/venv/lib/python3.9/site-packages/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/home/mikhail/venv/lib/python3.9/site-packages/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/home/mikhail/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.217", line 13, in forward
    layer_norm_wrapper = kernl_optimizer_layer_norm_layer_norm_wrapper(self_transformer_wte, layernorm);  layernorm = None
  File "/home/mikhail/kernl/src/kernl/optimizer/layer_norm.py", line 29, in layer_norm_wrapper
    return layer_norm(v, layernorm.weight, layernorm.bias, layernorm.eps)
  File "/home/mikhail/kernl/src/kernl/implementations/layer_norm.py", line 319, in layer_norm
    return LayerNorm.apply(x, weight, bias, eps, implementation, use_rms_norm)
  File "/home/mikhail/venv/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 116, in decorate_fwd
    return fwd(*_cast(args, cast_inputs), **_cast(kwargs, cast_inputs))
  File "/home/mikhail/kernl/src/kernl/implementations/layer_norm.py", line 290, in forward
    implementation[(M,)](
  File "/home/mikhail/venv/lib/python3.9/site-packages/triton/runtime/jit.py", line 106, in launcher
    return self.run(*args, grid=grid, **kwargs)
  File "<string>", line 42, in _layer_norm_fwd_fused_single_pass
  File "/home/mikhail/venv/lib/python3.9/site-packages/triton/compiler.py", line 1215, in compile
    asm, shared, kernel_name = _compile(fn, signature, device, constants, configs[0], num_warps, num_stages,
  File "/home/mikhail/venv/lib/python3.9/site-packages/triton/compiler.py", line 900, in _compile
    name, asm, shared_mem = _triton.code_gen.compile_ttir(backend, module, device, num_warps, num_stages, extern_libs, cc)
RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/fileJP3xUz, line 95; fatal   : Parsing error near ':': syntax error
ptxas fatal   : Ptx assembly aborted due to errors

----------------------------------------
ERROR:root:Error while processing frame
Traceback (most recent call last):
  File "<string>", line 21, in _layer_norm_fwd_fused_single_pass
KeyError: ('2-.-0-.-0-aced2afef9a9131c1822ef1dc83cefd3-cfed90d463fc30ccffb0eb2fd26372d3-a357695982511d203a134df772c7b4a1-2121719c12e3ab66746f4a57f276d42e-0f76008a374e725ca29ccb33f1ba668f-dc48432b6b79843e2f9c7ad2e7355f59-f40d73592c2578180d3d8e3f64e3957d-0dd03b0bd512a184b3512b278d9dfa59-d7c2e52f8151bec157e9a17a1ec37dd3', (torch.float16, torch.float16, torch.float16, torch.float16, torch.float32, torch.float32, 'i32', 'i32', 'fp32'), (True, False, 4096), (True, True, True, True, True, True, (True, False), (True, False), (False,)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mikhail/venv/lib/python3.9/site-packages/torchdynamo/output_graph.py", line 362, in call_user_compiler
    compiled_fn = self.compiler_fn(gm, self.example_inputs())
  File "/home/mikhail/kernl/src/kernl/model_optimization.py", line 46, in compiler
    return cuda_graphs_wrapper(gm, example_inputs, pool=pool)
  File "/home/mikhail/kernl/src/kernl/implementations/cuda_graph.py", line 40, in cuda_graphs_wrapper
    model(*inputs)
  File "/home/mikhail/venv/lib/python3.9/site-packages/torch/fx/graph_module.py", line 652, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/home/mikhail/venv/lib/python3.9/site-packages/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/home/mikhail/venv/lib/python3.9/site-packages/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/home/mikhail/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.217", line 13, in forward
    layer_norm_wrapper = kernl_optimizer_layer_norm_layer_norm_wrapper(self_transformer_wte, layernorm);  layernorm = None
  File "/home/mikhail/kernl/src/kernl/optimizer/layer_norm.py", line 29, in layer_norm_wrapper
    return layer_norm(v, layernorm.weight, layernorm.bias, layernorm.eps)
  File "/home/mikhail/kernl/src/kernl/implementations/layer_norm.py", line 319, in layer_norm
    return LayerNorm.apply(x, weight, bias, eps, implementation, use_rms_norm)
  File "/home/mikhail/venv/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 116, in decorate_fwd
    return fwd(*_cast(args, cast_inputs), **_cast(kwargs, cast_inputs))
  File "/home/mikhail/kernl/src/kernl/implementations/layer_norm.py", line 290, in forward
    implementation[(M,)](
  File "/home/mikhail/venv/lib/python3.9/site-packages/triton/runtime/jit.py", line 106, in launcher
    return self.run(*args, grid=grid, **kwargs)
  File "<string>", line 42, in _layer_norm_fwd_fused_single_pass
  File "/home/mikhail/venv/lib/python3.9/site-packages/triton/compiler.py", line 1215, in compile
    asm, shared, kernel_name = _compile(fn, signature, device, constants, configs[0], num_warps, num_stages,
  File "/home/mikhail/venv/lib/python3.9/site-packages/triton/compiler.py", line 900, in _compile
    name, asm, shared_mem = _triton.code_gen.compile_ttir(backend, module, device, num_warps, num_stages, extern_libs, cc)
RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/fileJP3xUz, line 95; fatal   : Parsing error near ':': syntax error
ptxas fatal   : Ptx assembly aborted due to errors


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mikhail/venv/lib/python3.9/site-packages/torchdynamo/eval_frame.py", line 148, in catch_errors
    return callback(frame, cache_size)
  File "/home/mikhail/venv/lib/python3.9/site-packages/torchdynamo/convert_frame.py", line 347, in _convert_frame
    result = inner_convert(frame, cache_size)
  File "/home/mikhail/venv/lib/python3.9/site-packages/torchdynamo/convert_frame.py", line 108, in _fn
    return fn(*args, **kwargs)
  File "/home/mikhail/venv/lib/python3.9/site-packages/torchdynamo/convert_frame.py", line 288, in _convert_frame_assert
    code = transform_code_object(frame.f_code, transform)
  File "/home/mikhail/venv/lib/python3.9/site-packages/torchdynamo/bytecode_transformation.py", line 338, in transform_code_object
    transformations(instructions, code_options)
  File "/home/mikhail/venv/lib/python3.9/site-packages/torchdynamo/convert_frame.py", line 264, in transform
    tracer.run()
  File "/home/mikhail/venv/lib/python3.9/site-packages/torchdynamo/symbolic_convert.py", line 312, in run
    and self.step()
  File "/home/mikhail/venv/lib/python3.9/site-packages/torchdynamo/symbolic_convert.py", line 290, in step
    getattr(self, inst.opname)(inst)
  File "/home/mikhail/venv/lib/python3.9/site-packages/torchdynamo/symbolic_convert.py", line 1335, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/home/mikhail/venv/lib/python3.9/site-packages/torchdynamo/output_graph.py", line 307, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/home/mikhail/venv/lib/python3.9/site-packages/torchdynamo/output_graph.py", line 348, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/mikhail/venv/lib/python3.9/site-packages/torchdynamo/output_graph.py", line 371, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torchdynamo.exc.BackendCompilerFailed: compiler raised RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/fileJP3xUz, line 95; fatal   : Parsing error near ':': syntax error
ptxas fatal   : Ptx assembly aborted due to errors


You can suppress this exception and fall back to eager by setting:
    torchdynamo.config.raise_on_backend_error = False

KeyError                                  Traceback (most recent call last)
File <string>:21, in _layer_norm_fwd_fused_single_pass(Out, A, Weight, Bias, Mean, Rstd, stride_row_a, N, eps, HAS_BIAS, IS_RMSNORM, BLOCK_SIZE, grid, num_warps, num_stages, extern_libs, stream, warmup)

KeyError: ('2-.-0-.-0-aced2afef9a9131c1822ef1dc83cefd3-cfed90d463fc30ccffb0eb2fd26372d3-a357695982511d203a134df772c7b4a1-2121719c12e3ab66746f4a57f276d42e-0f76008a374e725ca29ccb33f1ba668f-dc48432b6b79843e2f9c7ad2e7355f59-f40d73592c2578180d3d8e3f64e3957d-0dd03b0bd512a184b3512b278d9dfa59-d7c2e52f8151bec157e9a17a1ec37dd3', (torch.float16, torch.float16, torch.float16, torch.float16, torch.float32, torch.float32, 'i32', 'i32', 'fp32'), (True, False, 4096), (True, True, True, True, True, True, (True, False), (True, False), (False,)))

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
File ~/venv/lib/python3.9/site-packages/torchdynamo/output_graph.py:362, in OutputGraph.call_user_compiler(self, gm)
    361 try:
--> 362     compiled_fn = self.compiler_fn(gm, self.example_inputs())
    363     assert callable(compiled_fn), "compiler_fn did not return callable"

File ~/kernl/src/kernl/model_optimization.py:46, in optimize_model.<locals>.compiler(gm, example_inputs)
     45 dynamo_backend_ofi(gm)
---> 46 return cuda_graphs_wrapper(gm, example_inputs, pool=pool)

File ~/kernl/src/kernl/implementations/cuda_graph.py:40, in cuda_graphs_wrapper(model, inputs, copy_outputs, pool)
     39     for _ in range(2):
---> 40         model(*inputs)
     41 stream.synchronize()

File ~/venv/lib/python3.9/site-packages/torch/fx/graph_module.py:652, in GraphModule.recompile.<locals>.call_wrapped(self, *args, **kwargs)
    651 def call_wrapped(self, *args, **kwargs):
--> 652     return self._wrapped_call(self, *args, **kwargs)

File ~/venv/lib/python3.9/site-packages/torch/fx/graph_module.py:277, in _WrappedCall.__call__(self, obj, *args, **kwargs)
    276 else:
--> 277     raise e

File ~/venv/lib/python3.9/site-packages/torch/fx/graph_module.py:267, in _WrappedCall.__call__(self, obj, *args, **kwargs)
    266     else:
--> 267         return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
    268 except Exception as e:

File ~/venv/lib/python3.9/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used

File <eval_with_key>.217:13, in forward(self, input_ids)
     12 layernorm = self.self_transformer_h_0__ln_1
---> 13 layer_norm_wrapper = kernl_optimizer_layer_norm_layer_norm_wrapper(self_transformer_wte, layernorm);  layernorm = None
     14 linear_wrapper = kernl_optimizer_linear_linear_wrapper(layer_norm_wrapper, linear);  linear = None

File ~/kernl/src/kernl/optimizer/layer_norm.py:29, in layer_norm_wrapper(v, layernorm)
     27     layernorm.bias.data = layernorm.bias.data.half()
---> 29 return layer_norm(v, layernorm.weight, layernorm.bias, layernorm.eps)

File ~/kernl/src/kernl/implementations/layer_norm.py:319, in layer_norm(x, weight, bias, eps, implementation, use_rms_norm)
    311 def layer_norm(
    312     x: torch.Tensor,
    313     weight: torch.Tensor,
   (...)
    317     use_rms_norm: bool = False,
    318 ):
--> 319     return LayerNorm.apply(x, weight, bias, eps, implementation, use_rms_norm)

File ~/venv/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py:116, in custom_fwd.<locals>.decorate_fwd(*args, **kwargs)
    115     with autocast(enabled=False):
--> 116         return fwd(*_cast(args, cast_inputs), **_cast(kwargs, cast_inputs))
    117 else:

File ~/kernl/src/kernl/implementations/layer_norm.py:290, in LayerNorm.forward(ctx, x, weight, bias, eps, implementation, use_rms_norm)
    289 num_warps = min(max(BLOCK_SIZE // 256, 1), 8)
--> 290 implementation[(M,)](
    291     Out=out,
    292     A=a_arg,
    293     Weight=weight,
    294     Bias=bias if bias is not None else a_arg,
    295     Mean=mean,
    296     Rstd=std,
    297     stride_row_a=a_arg.stride(0),
    298     N=N,
    299     eps=eps,
    300     HAS_BIAS=bias is not None,
    301     IS_RMSNORM=use_rms_norm,
    302     BLOCK_SIZE=BLOCK_SIZE,
    303     num_warps=num_warps,
    304 )
    305 ctx.save_for_backward(x, mean, std, weight)

File ~/venv/lib/python3.9/site-packages/triton/runtime/jit.py:106, in KernelInterface.__getitem__.<locals>.launcher(*args, **kwargs)
    105 def launcher(*args, **kwargs):
--> 106     return self.run(*args, grid=grid, **kwargs)

File <string>:42, in _layer_norm_fwd_fused_single_pass(Out, A, Weight, Bias, Mean, Rstd, stride_row_a, N, eps, HAS_BIAS, IS_RMSNORM, BLOCK_SIZE, grid, num_warps, num_stages, extern_libs, stream, warmup)

File ~/venv/lib/python3.9/site-packages/triton/compiler.py:1215, in compile(fn, signature, device, constants, num_warps, num_stages, extern_libs, configs, cc, warm_cache_only)
   1212 if not fn_cache_manager.has_file(cubin_name) or \
   1213    not fn_cache_manager.has_file(data_name) or \
   1214    not fn_cache_manager.has_file(ptx_name):
-> 1215     asm, shared, kernel_name = _compile(fn, signature, device, constants, configs[0], num_warps, num_stages,
   1216                                         extern_libs, "cubin", cc)
   1217     metadata = {"name": kernel_name, "shared": shared, "num_warps": num_warps, "num_stages": num_stages}

File ~/venv/lib/python3.9/site-packages/triton/compiler.py:900, in _compile(fn, signature, device, constants, specialization, num_warps, num_stages, extern_libs, output, cc)
    899     extern_libs = dict()
--> 900 name, asm, shared_mem = _triton.code_gen.compile_ttir(backend, module, device, num_warps, num_stages, extern_libs, cc)
    901 return asm, shared_mem, name

RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/fileJP3xUz, line 95; fatal   : Parsing error near ':': syntax error
ptxas fatal   : Ptx assembly aborted due to errors


The above exception was the direct cause of the following exception:

BackendCompilerFailed                     Traceback (most recent call last)
Cell In [10], line 2
      1 with torch.inference_mode(), torch.cuda.amp.autocast():
----> 2     outputs = model.generate(
      3                 inputs["input_ids"],
      4                 **params
      5 
      6             )

File ~/venv/lib/python3.9/site-packages/torch/autograd/grad_mode.py:27, in _DecoratorContextManager.__call__.<locals>.decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

File ~/venv/lib/python3.9/site-packages/transformers/generation_utils.py:1500, in GenerationMixin.generate(self, inputs, max_length, min_length, do_sample, early_stopping, num_beams, temperature, top_k, top_p, typical_p, repetition_penalty, bad_words_ids, force_words_ids, bos_token_id, pad_token_id, eos_token_id, length_penalty, no_repeat_ngram_size, encoder_no_repeat_ngram_size, num_return_sequences, max_time, max_new_tokens, decoder_start_token_id, use_cache, num_beam_groups, diversity_penalty, prefix_allowed_tokens_fn, logits_processor, renormalize_logits, stopping_criteria, constraints, output_attentions, output_hidden_states, output_scores, return_dict_in_generate, forced_bos_token_id, forced_eos_token_id, remove_invalid_values, synced_gpus, exponential_decay_length_penalty, suppress_tokens, begin_suppress_tokens, forced_decoder_ids, **model_kwargs)
   1492     input_ids, model_kwargs = self._expand_inputs_for_generation(
   1493         input_ids,
   1494         expand_size=num_beams * num_return_sequences,
   1495         is_encoder_decoder=self.config.is_encoder_decoder,
   1496         **model_kwargs,
   1497     )
   1499     # 13. run beam sample
-> 1500     return self.beam_sample(
   1501         input_ids,
   1502         beam_scorer,
   1503         logits_processor=logits_processor,
   1504         logits_warper=logits_warper,
   1505         stopping_criteria=stopping_criteria,
   1506         pad_token_id=pad_token_id,
   1507         eos_token_id=eos_token_id,
   1508         output_scores=output_scores,
   1509         return_dict_in_generate=return_dict_in_generate,
   1510         synced_gpus=synced_gpus,
   1511         **model_kwargs,
   1512     )
   1514 elif is_group_beam_gen_mode:
   1515     if num_return_sequences > num_beams:

File ~/venv/lib/python3.9/site-packages/transformers/generation_utils.py:2612, in GenerationMixin.beam_sample(self, input_ids, beam_scorer, logits_processor, stopping_criteria, logits_warper, max_length, pad_token_id, eos_token_id, output_attentions, output_hidden_states, output_scores, return_dict_in_generate, synced_gpus, **model_kwargs)
   2608         break
   2610 model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
-> 2612 outputs = self(
   2613     **model_inputs,
   2614     return_dict=True,
   2615     output_attentions=output_attentions,
   2616     output_hidden_states=output_hidden_states,
   2617 )
   2619 if synced_gpus and this_peer_finished:
   2620     cur_len = cur_len + 1

File ~/venv/lib/python3.9/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

File ~/kernl/src/kernl/model_optimization.py:50, in optimize_model.<locals>.run(*args, **kwargs)
     48 def run(*args, **kwargs):
     49     with torchdynamo.optimize(compiler):
---> 50         return original_model.forward2(*args, **kwargs)

File ~/venv/lib/python3.9/site-packages/torchdynamo/eval_frame.py:148, in catch_errors_wrapper.<locals>.catch_errors(frame, cache_size)
    146         return None
    147     with compile_lock:
--> 148         return callback(frame, cache_size)
    149 except Exception:
    150     logging.basicConfig()

File ~/venv/lib/python3.9/site-packages/torchdynamo/convert_frame.py:347, in convert_frame.<locals>._convert_frame(frame, cache_size)
    345 counters["frames"]["total"] += 1
    346 try:
--> 347     result = inner_convert(frame, cache_size)
    348     counters["frames"]["ok"] += 1
    349     return result

File ~/venv/lib/python3.9/site-packages/torchdynamo/convert_frame.py:108, in wrap_convert_context.<locals>._fn(*args, **kwargs)
    106 torch.fx.graph_module._forward_from_src = fx_forward_from_src_skip_result
    107 try:
--> 108     return fn(*args, **kwargs)
    109 finally:
    110     torch._C._set_grad_enabled(prior_grad_mode)

File ~/venv/lib/python3.9/site-packages/torchdynamo/convert_frame.py:288, in convert_frame_assert.<locals>._convert_frame_assert(frame, cache_size)
    286 for attempt in itertools.count():
    287     try:
--> 288         code = transform_code_object(frame.f_code, transform)
    289         orig_code_map[code] = frame.f_code
    290         break

File ~/venv/lib/python3.9/site-packages/torchdynamo/bytecode_transformation.py:338, in transform_code_object(code, transformations, safe)
    334 assert len(code_options["co_varnames"]) == code_options["co_nlocals"]
    336 instructions = cleaned_instructions(code, safe)
--> 338 transformations(instructions, code_options)
    340 fix_vars(instructions, code_options)
    342 dirty = True

File ~/venv/lib/python3.9/site-packages/torchdynamo/convert_frame.py:264, in convert_frame_assert.<locals>._convert_frame_assert.<locals>.transform(instructions, code_options)
    253 nonlocal output
    254 tracer = InstructionTranslator(
    255     instructions,
    256     frame.f_code,
   (...)
    262     one_graph,
    263 )
--> 264 tracer.run()
    265 output = tracer.output
    266 assert output.output_instructions

File ~/venv/lib/python3.9/site-packages/torchdynamo/symbolic_convert.py:312, in InstructionTranslatorBase.run(self)
    307 def run(self):
    308     try:
    309         while (
    310             self.instruction_pointer is not None
    311             and not self.output.should_exit
--> 312             and self.step()
    313         ):
    314             pass
    315     except (
    316         exc.BackendCompilerFailed,
    317         exc.RestartAnalysis,
   (...)
    320         exc.Unsupported,
    321     ):

File ~/venv/lib/python3.9/site-packages/torchdynamo/symbolic_convert.py:290, in InstructionTranslatorBase.step(self)
    288     if not hasattr(self, inst.opname):
    289         unimplemented(f"missing: {inst.opname}")
--> 290     getattr(self, inst.opname)(inst)
    291     return inst.opname != "RETURN_VALUE"
    292 except Unsupported as exc:

File ~/venv/lib/python3.9/site-packages/torchdynamo/symbolic_convert.py:1335, in InstructionTranslator.RETURN_VALUE(self, inst)
   1333     raise exc.SkipFrame()
   1334 self.instruction_pointer = None
-> 1335 self.output.compile_subgraph(self)
   1336 self.output.add_output_instructions([create_instruction("RETURN_VALUE")])

File ~/venv/lib/python3.9/site-packages/torchdynamo/output_graph.py:307, in OutputGraph.compile_subgraph(self, tx, partial_convert)
    304 output = []
    305 if count_calls(self.graph) != 0 or len(pass2.graph_outputs) != 0:
    306     output.extend(
--> 307         self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
    308     )
    310     if len(pass2.graph_outputs) != 0:
    311         output.append(pass2.create_store(graph_output_var))

File ~/venv/lib/python3.9/site-packages/torchdynamo/output_graph.py:348, in OutputGraph.compile_and_call_fx_graph(self, tx, rv, root)
    346 gm.recompile()
    347 name = unique_id("__compiled_fn")
--> 348 compiled_fn = self.call_user_compiler(gm)
    349 compiled_fn = torchdynamo.disable(compiled_fn)
    350 counters["stats"]["unique_graphs"] += 1

File ~/venv/lib/python3.9/site-packages/torchdynamo/output_graph.py:371, in OutputGraph.call_user_compiler(self, gm)
    369     compiled_fn = gm.forward
    370     if config.raise_on_backend_error:
--> 371         raise BackendCompilerFailed(self.compiler_fn, e) from e
    372 return compiled_fn

BackendCompilerFailed: compiler raised RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/fileJP3xUz, line 95; fatal   : Parsing error near ':': syntax error
ptxas fatal   : Ptx assembly aborted due to errors


You can suppress this exception and fall back to eager by setting:
    torchdynamo.config.raise_on_backend_error = False
```

Python3.9, CUDA 11.6

**Comment by pommedeterresautee** [comment]
Do you know if there is a paper describing GPT-J architecture? Need to check if it matches what we do.

**Comment by hchoi-moveworks** [comment]
Hello @pommedeterresautee 

This model seems to be in huggingface hub
https://huggingface.co/EleutherAI/gpt-j-6b
