### ISSUE TITLE
CUDA: Error- illegal address when run bert e2e.ipynb on A30 gpu

### ISSUE THREAD

**Issue by chenxu001** [ELS-RD/kernl#194]
I run bert e2e.ipynb on A30 gpu，errors below:

> [2022-11-30 09:15:16,407] torch._dynamo.output_graph: [WARNING] ----------------------------------------
> 
> [2022-11-30 09:15:16,407] torch._dynamo.output_graph: [WARNING] TORCHDYNAMO: backend compiler failed
> 
> [2022-11-30 09:15:16,407] torch._dynamo.output_graph: [WARNING] CUDA: Error- illegal address
> Traceback (most recent call last):
>   File "<string>", line 21, in kernel_fma
> KeyError: ('2-.-0-.-0-1e8410f206c822547fb50e2ea86e45a6-7929002797455b30efce6e41eddc6b57-3aa563e00c5c695dd945e23b09a86848-f24b6aa9b101a518b6a4a6bddded372e-ff946bd4b3b4a4cbdf8cedc6e1c658e0-5c5e32ff210f3b7f56c98ca29917c25e-06f0df2d61979d629033f4a22eff5198-0dd03b0bd512a184b3512b278d9dfa59-d35ab04ae841e2714a253c523530b071', (torch.float16, None, torch.float16, torch.float16, torch.float16, 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'), (32, 8, 32, 32, 1, True, True, False, ''), (True, (False,), True, True, True, (False, False), (True, False), (True, False), (False, True), (False, False), (False, False), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True)))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/torch/_dynamo/output_graph.py", line 433, in call_user_compiler
>     compiled_fn = self.compiler_fn(gm, self.example_inputs())
>   File "/usr/local/lib/python3.9/dist-packages/torch/_dynamo/debug_utils.py", line 819, in debug_wrapper
>     compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
>   File "/kernl/src/kernl/model_optimization.py", line 33, in _compiler
>     return cuda_graphs_wrapper(gm, example_inputs, pool=_pool)
>   File "/kernl/src/kernl/implementations/cuda_graph.py", line 40, in cuda_graphs_wrapper
>     model(*inputs)
>   File "/usr/local/lib/python3.9/dist-packages/torch/fx/graph_module.py", line 660, in call_wrapped
>     return self._wrapped_call(self, *args, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/torch/fx/graph_module.py", line 279, in __call__
>     raise e
>   File "/usr/local/lib/python3.9/dist-packages/torch/fx/graph_module.py", line 269, in __call__
>     return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
>   File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1423, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "<eval_with_key>.130", line 30, in forward
>     linear_wrapper_13 = kernl_optimizer_linear_linear_wrapper(layer_norm_wrapper, linear_13);  linear_13 = None
>   File "/kernl/src/kernl/optimizer/linear.py", line 31, in linear_wrapper
>     return linear_layer(v, linear.weight, linear.bias, activation=activation)
>   File "/kernl/src/kernl/implementations/linear_layer.py", line 284, in linear_layer
>     return LinearLayer.apply(x, weight, bias, activation, act_inputs)
>   File "/usr/local/lib/python3.9/dist-packages/torch/cuda/amp/autocast_mode.py", line 104, in decorate_fwd
>     return fwd(*_cast(args, cast_inputs), **_cast(kwargs, cast_inputs))
>   File "/kernl/src/kernl/implementations/linear_layer.py", line 248, in forward
>     kernel_fma[grid](
>   File "/usr/local/lib/python3.9/dist-packages/triton/runtime/jit.py", line 106, in launcher
>     return self.run(*args, grid=grid, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/triton/runtime/autotuner.py", line 73, in run
>     timings = {config: self._bench(*args, config=config, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/triton/runtime/autotuner.py", line 73, in <dictcomp>
>     timings = {config: self._bench(*args, config=config, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/triton/runtime/autotuner.py", line 63, in _bench
>     return do_bench(kernel_call)
>   File "/usr/local/lib/python3.9/dist-packages/triton/testing.py", line 140, in do_bench
>     fn()
>   File "/usr/local/lib/python3.9/dist-packages/triton/runtime/autotuner.py", line 62, in kernel_call
>     self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages, **current)
>   File "/usr/local/lib/python3.9/dist-packages/triton/runtime/autotuner.py", line 200, in run
>     return self.fn.run(*args, **kwargs)
>   File "<string>", line 41, in kernel_fma
>   File "/usr/local/lib/python3.9/dist-packages/triton/compiler.py", line 1268, in compile
>     return CompiledKernel(name, so_cache_manager._make_path(so_name), fn_cache_manager.cache_dir, device)
>   File "/usr/local/lib/python3.9/dist-packages/triton/compiler.py", line 1301, in __init__
>     mod, func, n_regs, n_spills = _triton.code_gen.load_binary(metadata["name"], self.asm["cubin"], self.shared, device)
> RuntimeError: CUDA: Error- illegal address
> [2022-11-30 09:15:16,408] torch._dynamo.output_graph: [WARNING] ----------------------------------------
> 
> [2022-11-30 09:15:16,409] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT forward /usr/local/lib/python3.9/dist-packages/transformers/models/camembert/modeling_camembert.py line 1050

**Comment by chenxu001** [comment]
I used Docker image, the version is:

**Comment by chenxu001** [comment]
I used Docker image, the version is:
pytorch: 1.14.0.dev20221029+cu117
triton: 2.0.0.dev20221105
transformers: 4.24.0

**Comment by gaetansnl** [comment]
@chenxu001 Hello, could you retry with current main ?

**Comment by jonathlela** [comment]
I close the issue. Feel free to reopen a issue if the bug still persists.
