### ISSUE TITLE
bug: How to save the optimized model to file?

### ISSUE THREAD

**Issue by aaronchan90** [ELS-RD/kernl#313]
### Description

Hi, I'm trying to run kernl in production, and I need to save the optimized model into file. so Here is my problem:  How to save the optimized model to file?

### Steps to reproduce

Here is my code:
```
import torch
from transformers import AutoModel
from kernl.model_optimization import optimize_model

model_name = 'bert-base-uncased'

model = AutoModel.from_pretrained(model_name).eval().cuda()

optimize_model(model)

torch.save(model, "opt.bin")
```

and the error msg is :
```
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
<class 'transformers.models.bert.modeling_bert.BertModel'>
Traceback (most recent call last):
  File "//example.py", line 16, in <module>
    torch.save(model, "bertmodel.bin")
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 443, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 655, in _save
    pickler.dump(obj)
AttributeError: Can't pickle local object 'optimize_model.<locals>.run'
```

### Expected Behavior

save the optimized model into file

### Actual Behavior

catched a error msg like:
```
AttributeError: Can't pickle local object 'optimize_model.<locals>.run'
```

### Your environment

- Operating system and version (e.g. Ubuntu 20.04.2 LTS):
- Python version (e.g. Python 3.8.10):
- Python package manager (e.g. pip 21.1.2):
- etc.

### Self-service

- [ ] I would be willing to help fix this bug myself.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonathlela** [comment]
Hi @aaronchan90,

As far as I understand https://pytorch.org/get-started/pytorch-2.0/#serialization, we cannot serialize a model compiled with torchdynamo (which we use). We didn't test the `export` feature from torchdynamo though.
